language: python

python:
  – 2.7

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n webappdev python=$TRAVIS_PYTHON_VERSION pytest setuptools 
  - source activate webappdev
  - conda install conda-requirements.txt
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

before_script:
  - python manage.py syncdb –migrate –noinput

script:
  - python manage.py test webapp/apps/taxbrain
