name: pb_env
dependencies:
- python =2.7.14
- taxcalc =0.19.0
- btax =0.2.2
- ogusa =0.5.8
- numba >=0.33.0
- pandas >=0.22.0
- bokeh =0.12.7
- nomkl
- gevent
- pillow
- pyparsing

channels:
  - ospc
  - ospc/label/dev
  - defaults
  - conda-forge
