version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  flask:
    image: deploy:logg3
    command: /bin/bash -c "source activate aei_dropq" &&
      supervisord -c supervisord_local.conf
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/taxbrain_server'
    ports:
      - '8000:8000'

volumes:
    redis:
