version: '3'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
  redis:
    image: redis
