version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: FlaskDockerfile
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./
      dockerfile: CeleryDockerfile
    depends_on:
      - redis
  redis:
    image: redis
