version: '3'
services:
  flask:
    image: opensourcepolicycenter/flask
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 3000m
    ports:
      - 5050:5050
    depends_on:
      - redis
  celery:
    image: opensourcepolicycenter/celery
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.95"
          memory: 10000m
    depends_on:
      - redis
  redis:
    image: redis
