version: '3'
services:
  flask:
    image: opensourcepolicycenter/flask:latest
    ports:
      - 5050:5050
    depends_on:
      - redis
  celery:
    image: opensourcepolicycenter/celery:latest
    depends_on:
      - redis
  redis:
    image: redis
