version: '3'
services:
  flask:
    image: opensourcepolicycenter/flask
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 3000m
    ports:
      - "5000:5000"
    depends_on:
      - redis
  celery:
    image: opensourcepolicycenter/celery
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.9"
          memory: 8000m
    depends_on:
      - redis
  redis:
    image: redis
